version: '3'
services:
  frontend:

    image: node:22-alpine
    working_dir: /opt/app/src # WebLevelup/src
    volumes:
      - ./WebLevelup:/opt/app
    command: ["sh", "-c", "npm install && node server.js"]
    ports:
      - 3000:3005
    env_file:
      - .env
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - DATABASE_NAME=${DATABASE_NAME}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
