name: Deploy Frontend to Amazon EC2

on:
  push:
    branches:
      - main
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Frontend to EC2
    uses:  AlexKruger2815/WhatTypeOfSpiderAreYou/.github/workflows/deploy.yml@main
    secrets: 
      ENV_S3_URI: ${{ secrets.FRONTEND_ENV }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ROLE: ${{ secrets.AWS_ROLE }}
      EC2_SSH_KEY_NAME: ${{ secrets.EC2_SSH_KEY_NAME }}
      EC2_SSH_KEY_VALUE: ${{ secrets.EC2_SSH_KEY_VALUE }}
    with:
      SOURCE_DIR: WebLevelup
      TARGET_DIR: /home/ubuntu/Frontend
      DOCKER_SERVICE_NAME: frontend

