name: "DEV: Deploy Frontend to Amazon EC2"

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Frontend to EC2
    uses:  AlexKruger2815/WhatTypeOfSpiderAreYou/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      SOURCE_DIR: WebLevelup
      TARGET_DIR: /home/ubuntu/Frontend
      DOCKER_SERVICE_NAME: frontend
      INSTANCE_NAME: test-instance
      ENV_S3_URI: s3://spider-type-env-bucket/dev/frontend/.env