name: Deploy Backend to Amazon EC2

on:
  push:
    branches:
      - main
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Backend to EC2
    uses:  AlexKruger2815/WhatTypeOfSpiderAreYou/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      SOURCE_DIR: server
      TARGET_DIR: /home/ubuntu/Backend
      DOCKER_SERVICE_NAME: backend
