name: Deploy to Amazon EC2

on:
  push:
    branches:
      - main
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Frontend to EC2
    uses:  AlexKruger2815/WhatTypeOfSpiderAreYou/.github/workflows/deploy.yml@main
    with:
      SOURCE_DIR: WebLevelup
      TARGET_DIR: /home/ubuntu/Frontend
      DOCKER_SERVICE_NAME: frontend
