name: Deploy to EC2
on:
  push:
    branches:
      - main
      - dev
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - if: github.ref == 'refs/heads/main'
      run: echo "stage=prod" >> $GITHUB_ENV
    - if: github.ref != 'refs/heads/main'
      run: echo "stage=dev" >> $GITHUB_ENV

    - name: Check output
      run: |
        echo stage: ${{ env.stage }}
